name: goose
description:

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  #c
  cupertino_icons: ^1.0.8
  #f
  flutter:
    sdk: flutter
  #g
  get: 4.6.6
  get_it: 8.0.1
  go_router: 14.3.0
  #p
  path: 1.9.0
  #s
  sqflite: 2.4.0

dev_dependencies:
  #f
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
